services:

  db:
    build: ./db
    image: ${DOCKER_USERNAME:-omerbeithalahmy}/fruits-webapp-db:${TAG:-latest}
    container_name: mongo-db
    ports:
    - "27017:27017"
    networks:
    - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: always
  
  app:
    build: ./app
    image: ${DOCKER_USERNAME:-omerbeithalahmy}/fruits-webapp-app:${TAG:-latest}
    container_name: node-app
    ports:
    - "3000:3000"
    networks:
    - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  app-network:
    driver: bridge