name: Fruits Webapp CI

on:
  push:
    branches: ["main", "feat/webapp-provisioning"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: action/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker Compose Services
      run: docker-compose build